import type { ProductTypeDefinition } from "./auto";

export const babyProductTypes: ProductTypeDefinition[] = [
  {
    category: "BABY",
    type_name: "Baby supplement",
    primary_conversion_mechanism: "Parental protection instinct — showing pediatrician-backed nutritional gaps in infant diets triggers protective supplementation purchases",
    dominant_objection: "Is this safe for my baby's age and development stage, and is it pediatrician recommended?",
    required_proof: "Pediatrician endorsement or AAP guideline alignment, age-appropriate dosing transparency, and parent diary of observable improvements",
    content_style_affinity: ["pediatrician review", "parent daily routine", "milestone tracking", "ingredient safety breakdown", "new parent education"],
    anti_patterns: ["Making developmental milestone promises", "No pediatric professional involvement", "Adult supplement branding repackaged for babies"],
  },
  {
    category: "BABY",
    type_name: "Sleep aid",
    primary_conversion_mechanism: "Exhaustion-driven desperation — sleep-deprived parents will purchase anything with credible evidence of helping their baby sleep longer stretches",
    dominant_objection: "Is this safe for unsupervised sleep, and does it follow safe sleep guidelines?",
    required_proof: "Compliance with safe sleep guidelines explicitly stated, baby monitor footage of improved sleep patterns, and parent sleep diary over 7+ nights",
    content_style_affinity: ["sleep diary journey", "nursery routine", "monitor footage results", "pediatric sleep tips", "exhausted parent solidarity"],
    anti_patterns: ["Guaranteed sleep claims", "Showing unsafe sleep environments", "Ignoring safe sleep guidelines entirely", "Single-night success stories"],
  },
  {
    category: "BABY",
    type_name: "Feeding tool",
    primary_conversion_mechanism: "Mealtime frustration relief — footage of a previously fussy eater engaging with food using the right tool converts frustrated parents instantly",
    dominant_objection: "Will my baby actually use this or throw it on the floor like everything else?",
    required_proof: "Multiple babies at different ages engaging with the tool, mess comparison to alternatives, and dishwasher durability test",
    content_style_affinity: ["mealtime transformation", "baby-led weaning", "toddler feeding hack", "mess comparison", "age progression feeding"],
    anti_patterns: ["Only showing cooperative eaters", "Single age representation", "No mess or cleanup reality", "Staged perfect mealtime scenes"],
  },
  {
    category: "BABY",
    type_name: "Safety product",
    primary_conversion_mechanism: "Fear prevention — showing real household hazards from a baby's eye level triggers immediate childproofing urgency before an accident happens",
    dominant_objection: "Is this actually childproof or will my toddler figure it out in 30 seconds?",
    required_proof: "Toddler attempting to defeat the safety measure and failing, installation across different surface types, and adult ease-of-use demonstration",
    content_style_affinity: ["hazard reveal from baby height", "childproofing walkthrough", "toddler proof test", "new parent checklist", "safety milestone prep"],
    anti_patterns: ["Fear-mongering injury footage", "Only showing installation without toddler testing", "Claiming to prevent all accidents"],
  },
  {
    category: "BABY",
    type_name: "Skin care",
    primary_conversion_mechanism: "Gentle protection — showing sensitive baby skin reacting well to a product when others have caused irritation converts cautious parents seeking safe options",
    dominant_objection: "Is this truly free of harmful chemicals and fragrances, and is it dermatologist tested for infant skin?",
    required_proof: "Full ingredient list transparency, dermatologist or pediatrician endorsement, patch test documentation, and comparison to common irritating alternatives",
    content_style_affinity: ["ingredient transparency", "sensitive skin routine", "pediatric dermatologist review", "diaper rash solution", "bath time routine"],
    anti_patterns: ["Using adult skincare terminology and marketing", "No professional endorsement for infant use", "Hiding the full ingredient list"],
  },
  {
    category: "BABY",
    type_name: "Teething product",
    primary_conversion_mechanism: "Immediate soothing proof — footage of a visibly uncomfortable teething baby finding relief converts through the parental empathy and relief response",
    dominant_objection: "Is this safe for my baby to chew on, and does it contain BPA, phthalates, or other harmful materials?",
    required_proof: "Safety certification visibility (BPA-free, FDA-compliant), baby engaging with the product during active teething, and material safety documentation",
    content_style_affinity: ["teething relief demo", "safety certification showcase", "fussy baby transformation", "material safety deep dive", "teething survival kit"],
    anti_patterns: ["Using numbing agents without safety disclaimers", "Showing only calm babies", "No material safety certifications visible"],
  },
  {
    category: "BABY",
    type_name: "Travel accessory",
    primary_conversion_mechanism: "Travel anxiety reduction — showing a smooth travel experience with a baby using the right gear converts parents who dread traveling with infants",
    dominant_objection: "Is this airline approved and compact enough to not become another bulky item I have to lug around?",
    required_proof: "Real travel footage (airport, car, hotel) showing the product in action, size when folded or stored, and airline compliance verification",
    content_style_affinity: ["travel with baby vlog", "airport survival guide", "car trip essentials", "compact gear review", "first flight prep"],
    anti_patterns: ["Only showing the product at home", "Ignoring airline size and safety regulations", "Staged travel content without real journey context"],
  },
];
