import type { ProductTypeDefinition } from "./auto";

export const beautyProductTypes: ProductTypeDefinition[] = [
  {
    category: "BEAUTY",
    type_name: "Serum",
    primary_conversion_mechanism: "Visible skin transformation — close-up texture changes over a documented timeline create undeniable proof that drives purchase urgency",
    dominant_objection: "Will this actually work on my specific skin type or just cause breakouts like the last serum I tried?",
    required_proof: "Unfiltered close-up skin footage over 7-30 days showing texture, tone, or hydration improvement with consistent lighting",
    content_style_affinity: ["skin journey diary", "GRWM with application", "texture close-up", "ingredient breakdown", "dermatologist reaction"],
    anti_patterns: ["Heavy filters or ring-light-only footage that hides real texture", "Single-use reviews with no timeline", "Ingredient dumps without visible results"],
  },
  {
    category: "BEAUTY",
    type_name: "Cleanser",
    primary_conversion_mechanism: "Satisfying removal — watching makeup, sunscreen, and grime dissolve in real-time triggers the clean-skin dopamine response",
    dominant_objection: "Will it strip my skin and leave it tight and dry, or actually maintain my moisture barrier?",
    required_proof: "Full face cleanse removing visible makeup or sunscreen with post-cleanse skin that looks hydrated, not stripped",
    content_style_affinity: ["double cleanse routine", "makeup meltdown ASMR", "end of day wipe test", "pH balance demo"],
    anti_patterns: ["Applying to already-clean skin", "Only showing lather without removal results", "Skipping the post-cleanse skin feel check"],
  },
  {
    category: "BEAUTY",
    type_name: "SPF",
    primary_conversion_mechanism: "Fear of damage — UV camera footage showing invisible sun damage converts skeptics into daily SPF users instantly",
    dominant_objection: "Will it leave a white cast, feel greasy, or pill under my makeup?",
    required_proof: "Application on multiple skin tones showing no white cast, wear under makeup for a full day, and ideally UV camera coverage proof",
    content_style_affinity: ["UV camera reveal", "SPF under makeup test", "full day wear test", "skin tone range demo", "reapplication method"],
    anti_patterns: ["Only showing application on light skin", "Studio lighting that hides white cast", "No makeup layering test"],
  },
  {
    category: "BEAUTY",
    type_name: "Lip product",
    primary_conversion_mechanism: "Instant gratification — lip color and texture transformation is immediate and highly visual, driving impulse color-match purchases",
    dominant_objection: "Will this shade actually look like the swatch on my skin tone, and will it transfer onto everything?",
    required_proof: "Swatch on multiple skin tones, cup test for transfer, and wear check after eating or drinking",
    content_style_affinity: ["swatch comparison", "eat and drink test", "lip combo tutorial", "shade range lineup", "GRWM lip focus"],
    anti_patterns: ["Single skin tone swatches", "Fresh application only with no wear test", "Over-lined lips that misrepresent the product finish"],
  },
  {
    category: "BEAUTY",
    type_name: "Scalp treatment",
    primary_conversion_mechanism: "Problem-solution urgency — visible flaking, oiliness, or thinning footage creates personal identification and immediate purchase motivation",
    dominant_objection: "Is this actually treating the root cause or just masking symptoms temporarily?",
    required_proof: "Scalp close-ups before and after consistent use over 2-4 weeks showing reduced flaking, irritation, or improved density",
    content_style_affinity: ["scalp check close-up", "wash day routine", "trichologist review", "progress timeline", "ingredient science"],
    anti_patterns: ["Only showing the product bottle without scalp footage", "Single-use miracle claims", "Avoiding the uncomfortable before footage"],
  },
  {
    category: "BEAUTY",
    type_name: "Hair tool",
    primary_conversion_mechanism: "Dramatic transformation — the side-by-side of unstyled vs. styled hair in under 60 seconds sells the tool through pure visual impact",
    dominant_objection: "Will it damage my hair with heat, and does it work on my specific hair type and texture?",
    required_proof: "Demo on at least 2 different hair textures showing styling result and a heat-damage check or temperature display",
    content_style_affinity: ["one-tool styling", "hair type comparison", "speed styling challenge", "before-after split screen"],
    anti_patterns: ["Only demoing on already-styled or blown-out hair", "Single hair type representation", "Ignoring heat settings and damage concerns"],
  },
  {
    category: "BEAUTY",
    type_name: "Eye cream",
    primary_conversion_mechanism: "Age anxiety — close-up under-eye footage highlighting dark circles, puffiness, or fine lines triggers preventive or corrective purchase behavior",
    dominant_objection: "Eye creams never work — is this just an overpriced moisturizer in a small jar?",
    required_proof: "Macro lens under-eye footage over 14+ days showing measurable reduction in puffiness, darkness, or fine lines with consistent lighting",
    content_style_affinity: ["morning depuff routine", "macro skin journey", "eye cream layering", "before-after close-up", "ingredient deep dive"],
    anti_patterns: ["Concealer applied after the eye cream making results ambiguous", "Single morning demo with no timeline", "Filtered footage that smooths fine lines digitally"],
  },
  {
    category: "BEAUTY",
    type_name: "Toner",
    primary_conversion_mechanism: "Routine optimization — toner converts through the educated skincare audience who understands pH balance and prep steps",
    dominant_objection: "Is toner even necessary or is it just an extra step that does nothing?",
    required_proof: "pH strip test showing skin balance improvement, absorption demo of following products with and without toner prep",
    content_style_affinity: ["skincare routine order", "pH balance demo", "cotton pad reveal", "layering technique", "skip care debate"],
    anti_patterns: ["Presenting it as a standalone miracle product", "No demonstration of how it enhances the rest of the routine", "Ignoring the skeptic audience entirely"],
  },
  {
    category: "BEAUTY",
    type_name: "Mask",
    primary_conversion_mechanism: "Self-care ritual — the mask is as much about the pampering experience as the results, converting through aesthetic routine content",
    dominant_objection: "Is this worth the price for a single-use or weekly product when my serum does the heavy lifting?",
    required_proof: "Immediate post-mask glow or texture change captured in consistent lighting, plus comparison to bare routine results",
    content_style_affinity: ["self-care night routine", "mask and chill aesthetic", "peel-off satisfaction", "sheet mask comparison", "spa day at home"],
    anti_patterns: ["Only showing the mask on the face without removal results", "Glamorizing the experience with no efficacy proof", "Using filters during the reveal"],
  },
];
