import type { ProductTypeDefinition } from "./auto";

export const homeProductTypes: ProductTypeDefinition[] = [
  {
    category: "HOME",
    type_name: "Cleaning tool",
    primary_conversion_mechanism: "Satisfying grime removal — watching years of buildup disappear in a single wipe or spray creates visceral must-have urgency",
    dominant_objection: "Is this actually more effective than what I already have under my sink?",
    required_proof: "Head-to-head cleaning test against a common household product on the same surface, showing clear performance difference",
    content_style_affinity: ["satisfying clean", "grime removal ASMR", "cleaning hack", "product showdown", "deep clean transformation"],
    anti_patterns: ["Pre-cleaned surfaces presented as dirty", "Only cleaning easy messes", "No comparison to existing solutions"],
  },
  {
    category: "HOME",
    type_name: "Storage solution",
    primary_conversion_mechanism: "Space revelation — showing a cluttered closet, pantry, or drawer transformed into organized perfection triggers immediate declutter motivation and purchase",
    dominant_objection: "Will these actually fit my specific space, and will I maintain the organization beyond a week?",
    required_proof: "Full space transformation with measurements shown, items loaded at real capacity, and ideally a follow-up showing maintained organization",
    content_style_affinity: ["pantry organization", "closet transformation", "fridge restock", "drawer declutter ASMR", "small space hacks"],
    anti_patterns: ["Empty container beauty shots", "Only organizing already minimal spaces", "No measurements or fit demonstration"],
  },
  {
    category: "HOME",
    type_name: "Air quality device",
    primary_conversion_mechanism: "Invisible threat awareness — showing air quality sensor readings in a normal home revealing poor AQI numbers shocks viewers into protective purchasing",
    dominant_objection: "Is this actually filtering or purifying anything, or is it just a fan with a HEPA sticker?",
    required_proof: "Air quality meter readings before and after running the device in a closed room, showing measurable particulate or VOC reduction",
    content_style_affinity: ["air quality test reveal", "allergy season survival", "bedroom air purification", "filter change comparison", "sensor data demo"],
    anti_patterns: ["Only showing the device running with no measurement", "Clean room demos that start with good air quality", "Spec-sheet content without real-world testing"],
  },
  {
    category: "HOME",
    type_name: "Pest control",
    primary_conversion_mechanism: "Disgust-driven urgency — footage of pest evidence (droppings, damage, live sightings) creates immediate need to eliminate the problem",
    dominant_objection: "Is this safe around kids and pets, and does it actually work or just repel temporarily?",
    required_proof: "Effectiveness demonstration with visible results, safety certifications visible, and pet or child safety context addressed",
    content_style_affinity: ["pest evidence reveal", "trap check results", "safe solution demo", "seasonal prevention guide", "exterminator tips"],
    anti_patterns: ["Graphic pest footage without content warnings", "Claiming permanent elimination from a single use", "Ignoring safety concerns for households with pets or children"],
  },
  {
    category: "HOME",
    type_name: "Laundry aid",
    primary_conversion_mechanism: "Stain rescue drama — the hopeless stain that everyone has given up on being completely removed creates powerful before-after conversion",
    dominant_objection: "Will this damage fabric colors or texture while removing the stain?",
    required_proof: "Multiple stain types (wine, grease, grass, blood) tested on different fabric colors showing removal without color damage",
    content_style_affinity: ["stain removal challenge", "laundry hack", "fabric rescue", "product comparison test", "laundry day routine"],
    anti_patterns: ["Only testing on white fabrics", "Fresh stains that any product could remove", "Single stain type demonstration"],
  },
  {
    category: "HOME",
    type_name: "Organization system",
    primary_conversion_mechanism: "Life simplification — showing a chaotic entryway, garage, or utility space become systematically organized converts through the mental clarity promise",
    dominant_objection: "Is this modular enough for my space, or will I need to buy 5 different systems to make it work?",
    required_proof: "Full room or zone transformation showing the complete system working together, with different configuration options demonstrated",
    content_style_affinity: ["room transformation", "modular system build", "garage organization", "entryway setup", "rental-friendly install"],
    anti_patterns: ["Showing individual pieces without the complete system", "Only perfect homes that do not need organization", "Ignoring installation difficulty and wall damage"],
  },
  {
    category: "HOME",
    type_name: "Smart home device",
    primary_conversion_mechanism: "Convenience multiplication — showing how one device eliminates a daily friction point converts through accumulated time and effort savings",
    dominant_objection: "Will this work with my existing smart home ecosystem or create another incompatible island?",
    required_proof: "Live integration demo with major platforms (Alexa, Google Home, HomeKit), setup time shown, and daily use scenario",
    content_style_affinity: ["smart home tour", "daily automation showcase", "setup timelapse", "voice command compilation", "ecosystem integration guide"],
    anti_patterns: ["Showing only the hardware without software integration", "Scripted voice commands that hide response lag", "Ignoring WiFi reliability issues"],
  },
  {
    category: "HOME",
    type_name: "Bathroom accessory",
    primary_conversion_mechanism: "Aesthetic upgrade — showing a dated bathroom transformed with a few key accessories converts through the low-cost renovation alternative appeal",
    dominant_objection: "Will this stick, mount, or hold up in a humid bathroom environment without falling apart?",
    required_proof: "Installation in a real bathroom with humidity exposure, weight-load test for mounted items, and 30-day durability check",
    content_style_affinity: ["bathroom makeover", "rental upgrade", "shower organization", "aesthetic bathroom tour", "adhesive durability test"],
    anti_patterns: ["Only showing products in a dry studio setting", "Ignoring humidity and water exposure", "New bathroom styling that hides the upgrade potential"],
  },
];
