import type { ProductTypeDefinition } from "./auto";

export const petProductTypes: ProductTypeDefinition[] = [
  {
    category: "PET",
    type_name: "Supplement",
    primary_conversion_mechanism: "Pet parent guilt — footage of a senior dog struggling with joints or a cat with dull coat triggers emotional protective purchasing",
    dominant_objection: "Is this actually vet-approved or just pet industry marketing with no real efficacy?",
    required_proof: "Before-after mobility or coat footage over 2-4 weeks, plus vet endorsement or clinical ingredient backing",
    content_style_affinity: ["senior pet journey", "vet recommendation", "daily routine integration", "mobility transformation", "pet parent testimony"],
    anti_patterns: ["Only showing the product packaging or treat form", "Human-focused content with pet as prop", "No timeline or progression footage"],
  },
  {
    category: "PET",
    type_name: "Interactive toy",
    primary_conversion_mechanism: "Entertainment proxy — watching another pet go wild with excitement over a toy triggers the desire to see your own pet that happy",
    dominant_objection: "Will my pet actually play with this or ignore it after 5 minutes like every other toy?",
    required_proof: "Multiple pets of different breeds and energy levels engaging with the toy over separate sessions, not just initial curiosity",
    content_style_affinity: ["pet reaction compilation", "bored pet transformation", "puzzle toy challenge", "multi-pet playtest", "enrichment routine"],
    anti_patterns: ["Only one pet featured with treat-lured engagement", "Showing only the first 10 seconds of excitement", "Heavily edited clips hiding disinterest"],
  },
  {
    category: "PET",
    type_name: "Grooming tool",
    primary_conversion_mechanism: "Visible shedding relief — the mountain of fur removed in a single session creates visceral purchase urgency for shedding-exhausted pet owners",
    dominant_objection: "Will this hurt my pet or pull their undercoat in a damaging way?",
    required_proof: "Full grooming session showing pet comfort throughout, fur yield result, and comparison to a standard brush",
    content_style_affinity: ["satisfying fur removal", "shedding season rescue", "grooming ASMR", "pet spa day", "breed-specific demo"],
    anti_patterns: ["Only showing the fur pile without the grooming process", "Using a cooperative pet breed that tolerates anything", "No comfort or reaction footage from the pet"],
  },
  {
    category: "PET",
    type_name: "Premium food",
    primary_conversion_mechanism: "Ingredient transparency — showing real meat, whole ingredients, and comparing to competitor filler lists converts health-conscious pet parents",
    dominant_objection: "Is the premium price actually justified by better nutrition or is it just better marketing?",
    required_proof: "Ingredient comparison to mainstream brands, pet preference test (choosing this food over alternatives), and visible coat or energy improvements over time",
    content_style_affinity: ["ingredient comparison", "food taste test", "what I feed my pet", "label reading education", "vet nutritionist review"],
    anti_patterns: ["Only showing pretty packaging", "Price justification without nutritional evidence", "Single feeding clip without any health outcome tracking"],
  },
  {
    category: "PET",
    type_name: "Bed/comfort",
    primary_conversion_mechanism: "Comfort anthropomorphism — watching a pet sink into a bed and fall asleep instantly triggers the same comfort-purchase psychology as human bedding",
    dominant_objection: "Will it flatten out in a month like every other pet bed, and is it actually washable?",
    required_proof: "Pet choosing the bed over alternatives, bounce-back test after weeks of use, and washing machine cycle demo",
    content_style_affinity: ["pet bed review", "nap cam footage", "comfort comparison test", "durability check", "senior pet comfort"],
    anti_patterns: ["Forced pet placement on the bed", "Brand new bed only with no long-term durability evidence", "Ignoring washability and cover removal"],
  },
  {
    category: "PET",
    type_name: "Calming product",
    primary_conversion_mechanism: "Desperation relief — pet owners dealing with storm anxiety, separation anxiety, or travel stress will try anything that shows real calming results",
    dominant_objection: "Does this actually calm the pet or is the owner just projecting calmness onto normal behavior?",
    required_proof: "Before-and-after behavior footage during a known trigger event (fireworks, thunderstorm, car ride) with visible anxiety reduction",
    content_style_affinity: ["storm anxiety rescue", "travel calm test", "separation anxiety diary", "vet behaviorist input", "fireworks night survival"],
    anti_patterns: ["Showing an already calm pet and claiming the product did it", "No trigger event context", "Testimonials without any behavioral footage"],
  },
  {
    category: "PET",
    type_name: "Dental care",
    primary_conversion_mechanism: "Neglect awareness — close-up of tartar buildup or yellow teeth shocks pet owners into realizing they have been neglecting dental health",
    dominant_objection: "Will my pet actually tolerate this, and is it as effective as a professional cleaning?",
    required_proof: "Teeth close-up before and after consistent use over 2-4 weeks, plus pet tolerance footage during application",
    content_style_affinity: ["teeth check close-up", "dental routine demo", "vet dental tips", "tartar removal progression", "pet breath test"],
    anti_patterns: ["Only showing the product without teeth footage", "Single-use demo claiming instant results", "Avoiding the pet tolerance conversation"],
  },
  {
    category: "PET",
    type_name: "Training tool",
    primary_conversion_mechanism: "Behavior breakthrough — footage of a badly behaved pet responding to training within minutes converts frustrated pet owners instantly",
    dominant_objection: "Does this use humane methods, and will it work on my stubborn breed?",
    required_proof: "Real training session with an untrained pet showing progressive behavior improvement, plus demonstration across different breeds",
    content_style_affinity: ["training transformation", "leash reactivity fix", "puppy first session", "breed-specific training", "trainer endorsement"],
    anti_patterns: ["Pre-trained pets pretending to learn", "Single breed representation", "Skipping the method explanation that proves humane approach"],
  },
];
