import type { ProductTypeDefinition } from "./auto";

export const techProductTypes: ProductTypeDefinition[] = [
  {
    category: "TECH",
    type_name: "Wireless charger",
    primary_conversion_mechanism: "Desk aesthetic upgrade — the clean cable-free setup triggers viewers who are tired of tangled nightstand and desk clutter",
    dominant_objection: "Is it actually fast enough to replace my wired charger, and will it work through my phone case?",
    required_proof: "Side-by-side charge speed test vs wired charger, through-case charging demo, and alignment tolerance test",
    content_style_affinity: ["desk setup tour", "nightstand organization", "charge speed race", "cable elimination", "tech aesthetic"],
    anti_patterns: ["Only showing the charger as a standalone product without a real setup", "Ignoring charge speed comparisons", "Not testing with popular phone cases"],
  },
  {
    category: "TECH",
    type_name: "Dash cam",
    primary_conversion_mechanism: "Protection urgency — caught-on-camera footage of near misses and insurance fraud triggers immediate security-purchase behavior",
    dominant_objection: "Will the video quality hold up at night and actually be usable for insurance claims?",
    required_proof: "Side-by-side day and night footage with readable plates, plus parking mode capture and app interface walkthrough",
    content_style_affinity: ["caught on camera", "night vision comparison", "road trip footage", "installation guide", "insurance story"],
    anti_patterns: ["Spec-sheet-heavy content without real footage samples", "Only daytime demos", "Skipping the mobile app and cloud features"],
  },
  {
    category: "TECH",
    type_name: "Smart device",
    primary_conversion_mechanism: "Automation envy — watching someone control their entire environment with voice or a single tap creates lifestyle upgrade desire",
    dominant_objection: "Will it actually work reliably with my existing ecosystem or become another frustrating smart home device?",
    required_proof: "Live demo of seamless integration with major ecosystems (Alexa, Google, HomeKit) including voice commands and automation triggers",
    content_style_affinity: ["smart home tour", "automation routine", "voice command demo", "ecosystem integration", "lazy genius hack"],
    anti_patterns: ["Scripted demos that hide connectivity lag", "Only showing one ecosystem", "Ignoring setup complexity and pairing frustrations"],
  },
  {
    category: "TECH",
    type_name: "Phone case",
    primary_conversion_mechanism: "Identity expression plus protection anxiety — the case is the most visible tech accessory and drop-test content triggers both style and safety purchases",
    dominant_objection: "Does it actually protect on drops or is it all looks with zero shock absorption?",
    required_proof: "Real drop test from pocket and table height onto concrete, plus MagSafe or accessory compatibility check",
    content_style_affinity: ["drop test challenge", "case collection showcase", "style matching outfit", "slim vs rugged comparison", "MagSafe test"],
    anti_patterns: ["Only showing the case in hand without any protection test", "Controlled drops onto carpet", "Ignoring wireless charging and accessory compatibility"],
  },
  {
    category: "TECH",
    type_name: "Bluetooth speaker",
    primary_conversion_mechanism: "Social proof through experience — showing the speaker in real social settings (beach, BBQ, shower) converts through aspirational lifestyle association",
    dominant_objection: "Does it actually sound good for its size or is it just loud with no bass?",
    required_proof: "Audio sample in real environments (not studio), waterproof or durability test, and size-to-sound surprise demo",
    content_style_affinity: ["outdoor sound test", "shower speaker review", "size comparison surprise", "party setup", "travel essential"],
    anti_patterns: ["Studio audio tests that do not represent real-world performance", "Spec-reading without listening demos", "Ignoring battery life and portability"],
  },
  {
    category: "TECH",
    type_name: "Portable power",
    primary_conversion_mechanism: "Dead battery anxiety — showing a phone die at 1% in a critical moment then reviving it creates immediate preparedness purchase motivation",
    dominant_objection: "How many full charges does it actually deliver, and is it small enough to carry daily?",
    required_proof: "Full charge cycle count on a real phone, pocket or bag size comparison, and charging speed measurement",
    content_style_affinity: ["dead phone rescue", "travel essential kit", "EDC showcase", "charge race", "festival survival"],
    anti_patterns: ["Only showing mAh numbers without real charge count", "Ignoring physical size and weight", "Not testing charging speed under real use"],
  },
  {
    category: "TECH",
    type_name: "Smart home",
    primary_conversion_mechanism: "Convenience revelation — showing a single device automating a tedious daily task converts through the time-saving realization",
    dominant_objection: "Is the setup actually simple or will I spend hours troubleshooting connectivity issues?",
    required_proof: "Unboxing-to-working demo in under 5 minutes, showing real app setup and first automation trigger",
    content_style_affinity: ["setup speedrun", "morning routine automation", "before-after home workflow", "smart home beginner guide"],
    anti_patterns: ["Skipping the setup process entirely", "Only showing the polished end result", "Hiding the app interface and configuration steps"],
  },
  {
    category: "TECH",
    type_name: "Cable organizer",
    primary_conversion_mechanism: "Chaos-to-order satisfaction — the before-after of tangled cables becoming clean lines triggers immediate organizational impulse",
    dominant_objection: "Will this actually stay organized after a week or will cables slip out and tangle again?",
    required_proof: "Full desk cable management transformation with a follow-up showing the setup still clean after daily plug and unplug cycles",
    content_style_affinity: ["desk transformation", "cable management ASMR", "setup tour", "organization timelapse", "WFH upgrade"],
    anti_patterns: ["Only showing the clips or channels empty", "Single cable demos that do not represent real desk complexity", "No follow-up on durability of organization"],
  },
];
