import type { ProductTypeDefinition } from "./auto";

export const wellnessProductTypes: ProductTypeDefinition[] = [
  {
    category: "WELLNESS",
    type_name: "Supplement capsule",
    primary_conversion_mechanism: "Routine simplicity — showing a single capsule fitting seamlessly into a morning routine converts through the low-effort health improvement promise",
    dominant_objection: "Supplements never work — is there any real science behind this or just placebo marketing?",
    required_proof: "Third-party lab testing certificates, clinical ingredient references, and user journey over 30-60 days with measurable markers",
    content_style_affinity: ["morning routine integration", "ingredient deep dive", "30-day challenge", "blood work before-after", "doctor reaction"],
    anti_patterns: ["Miracle cure language", "Single-day reviews", "Celebrity endorsement without any scientific backing", "Ignoring the bioavailability conversation"],
  },
  {
    category: "WELLNESS",
    type_name: "Powder supplement",
    primary_conversion_mechanism: "Ritual aesthetic — the mixing, swirling, and color of powder supplements creates visually satisfying content that converts through aspirational wellness routines",
    dominant_objection: "Does it taste terrible and do I actually absorb more from powder vs capsule form?",
    required_proof: "Honest taste reaction from multiple people, dissolution and mixability demo, and absorption or bioavailability comparison",
    content_style_affinity: ["morning drink ritual", "taste test reaction", "mixability demo", "stack recipe", "wellness routine ASMR"],
    anti_patterns: ["Only showing the aesthetic mix without taste feedback", "Hiding the powder in a smoothie that masks all flavor", "No discussion of absorption vs capsule alternatives"],
  },
  {
    category: "WELLNESS",
    type_name: "Sleep aid",
    primary_conversion_mechanism: "Desperation purchase — chronic poor sleepers will try anything, and real sleep tracking data showing improvement is the ultimate conversion proof",
    dominant_objection: "Will I become dependent on this, and will it leave me groggy in the morning?",
    required_proof: "Sleep tracker data (Oura, Apple Watch, Whoop) showing improved sleep scores over 7+ nights, plus morning alertness self-report",
    content_style_affinity: ["sleep tracker reveal", "nighttime routine", "morning energy comparison", "ingredient safety breakdown", "sleep hygiene tips"],
    anti_patterns: ["Single-night miracle claims", "No objective sleep data", "Ignoring dependency and grogginess concerns", "Showing someone falling asleep as proof"],
  },
  {
    category: "WELLNESS",
    type_name: "Posture corrector",
    primary_conversion_mechanism: "Pain-point identification — side-profile footage showing terrible posture makes viewers physically uncomfortable and drives corrective purchases",
    dominant_objection: "Will it actually retrain my posture or just act as a crutch I become dependent on?",
    required_proof: "Side-profile posture comparison over 2+ weeks of use, comfort review during a full workday, and evidence of posture improvement without the device",
    content_style_affinity: ["desk worker posture check", "side profile transformation", "WFH ergonomic setup", "comfort all-day test", "physical therapist review"],
    anti_patterns: ["Only showing the correction while wearing the device", "No long-term retraining evidence", "Ignoring comfort during extended wear"],
  },
  {
    category: "WELLNESS",
    type_name: "Topical treatment",
    primary_conversion_mechanism: "Visible relief — showing redness, inflammation, or pain points visibly reduced after application creates powerful before-after conversion",
    dominant_objection: "Is this just a temporary numbing effect or does it actually treat the underlying issue?",
    required_proof: "Application footage with visible reduction in redness or swelling, duration of relief measured in hours, and comparison to doing nothing",
    content_style_affinity: ["application close-up", "pain relief timeline", "active recovery routine", "ingredient transparency", "physical therapist endorsement"],
    anti_patterns: ["Claiming to cure conditions", "No visible before state to compare against", "Single application without tracking relief duration"],
  },
  {
    category: "WELLNESS",
    type_name: "Recovery tool",
    primary_conversion_mechanism: "Athletic identity — massage guns and recovery tools convert through the aspirational athlete identity and the immediate satisfying relief footage",
    dominant_objection: "Is this actually better than a foam roller or just an expensive vibrating gadget?",
    required_proof: "Range-of-motion improvement test before and after use, comparison to manual recovery, and muscle soreness tracking over workout cycles",
    content_style_affinity: ["post-workout recovery", "ROM comparison test", "athlete endorsement", "muscle group targeting guide", "travel recovery kit"],
    anti_patterns: ["Using it on relaxed muscles with no exercise context", "Only showing the satisfying percussion without measurable outcomes", "Ignoring the noise and weight concerns"],
  },
  {
    category: "WELLNESS",
    type_name: "Breathing device",
    primary_conversion_mechanism: "Stress-relief demonstration — real-time heart rate or HRV improvement during a breathing session creates undeniable biometric conversion proof",
    dominant_objection: "Can I not just breathe deeply without a device? What does this add?",
    required_proof: "HRV or heart rate data during device-guided vs unguided breathing showing measurable improvement, plus user experience of guided sessions",
    content_style_affinity: ["biometric live demo", "stress test experiment", "mindfulness routine", "HRV tracking journey", "anxiety management toolkit"],
    anti_patterns: ["Vague relaxation claims without any data", "Spiritual or pseudoscience framing", "No comparison to free breathing techniques"],
  },
  {
    category: "WELLNESS",
    type_name: "Blue light glasses",
    primary_conversion_mechanism: "Screen-time guilt — showing daily screen hours triggers the protective health investment for anyone spending 8+ hours on devices",
    dominant_objection: "Is blue light filtering actually proven to reduce eye strain or is this debunked science?",
    required_proof: "Spectrophotometer or blue light meter showing actual light filtration percentage, plus user eye strain diary over a workweek",
    content_style_affinity: ["screen time reveal", "workday comfort test", "style and function review", "eye strain diary", "optometrist reaction"],
    anti_patterns: ["Making medical eye health claims", "Ignoring the scientific debate entirely", "Only showcasing frames as fashion with no filtration proof"],
  },
];
